name: weather_app
description: Weather app with bloc architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  recase: ^4.1.0
  weather_icons: ^3.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  location: ^4.4.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  image_path: "assets/icon/launcher.png"
  android: false
  ios: true
  min_sdk_android: 26
  adaptive_icon_background: "assets/icon/launcher_background.png"
  adaptive_icon_foreground: "assets/icon/launcher.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/launcher.png"
    background_color: "#3F51B5"
    theme_color: "#3F51B5"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
